test: init cypress and create smoke tests
bcgov/nr-frontend-starting-app pull request #19
Opened 2022-10-06 13:31 UTC by dogivalfer

# Description

Initialized Cypress with all the configuration needed and a few smoke tests to validate the config.

Solves # [FSADT2-46](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-46)

## Type of change

- [ x] New feature (non-breaking change which adds functionality)
- [ x] This change requires a documentation update

# How Has This Been Tested?

Tested locally with the application pointing to the test environment.

## Checklist

- [ x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
- [ x] Any dependent changes have already been accepted and merged

## Further comments

2022-10-11 19:49 UTC, RMCampos requested changes
Just a few lint issues. Great job!! 🥳

2022-10-11 19:49 UTC, RMCampos commented on cypress/e2e/smoke-test/user-page.cy.ts
> +});
Same here. Few check style issues :/

2022-10-12 15:08 UTC, dogivalfer commented on cypress/support/commands.ts
> +
Fixed all the lint problems, thanks for the catch! :+1:

2022-10-14 16:35 UTC, RMCampos approved these changes
LGTM. Good job!! 💯

2022-10-14 17:13 UTC, merged